language: python
python:
  - 2.7
  - 3.5
  - 3.7

install:
  - python setup.py install
  - pip install pytest-cov
  - pip install codecov

script:
  - py.test --cov=./src ./tests

# Push the results back to codecov
after_success:
  - codecov
